<?php global $fragranceCollective_modName, $fragranceCollective_modDescription; ?>

<?php $mod_fragranceCollective = $TC->modules['mod_fragranceCollective'] ?? false; ?>

<?php $TC->the_header('admin'); ?>
<?php $TC->the_navbar('admin'); ?>

<div class="admin-bg"></div>

<div class="admin-container navToggle"> <!-- .navToggle -->
	<div class="admin-container-left">
				<?php $TC->the_sidebar('admin'); ?>
			</div>
	<div class="admin-container-right">
		<div class="content-container">
			<div class="row">
				<?php
					$mod_header_data = array(
						"mod_name" => "mod_fragranceCollective",
						"mod_name_lang" => $fragranceCollective_modName[$GLOBALS['lang']],
						"mod_description" => $fragranceCollective_modDescription[$GLOBALS['lang']]
					);
				?>
				<?php $TC->the_mod_header($mod_header_data); ?>

				<?php
					// If Module is activated and dependencies are loaded
					if($mod_fragranceCollective !== false && @$mod_fragranceCollective->mod_isOperable) {
				?>

					<section id="highlighted_layer" class="widget-squares col-md-12 row">
						<div class="col-md-12"><?php
							$TC->load_widget(array(
								"mod_name" => "mod_fragranceCollective",
								"widget_name" => "fragrance_combination_management_widget"
							), [], false);
						?></div>
					</section>

					<section class="widget-squares col-md-12 row">
						<div class="col-md-12"></div>
					</section>

				<?php } else if($mod_fragranceCollective !== false && (bool)@$mod_fragranceCollective->mod_isOperable === false) { ?>

					<section id="highlighted_layer" class="widget-squares col-md-12 row">
						<div class="col-md-12">
							<div class="card" style="padding: 0.25rem 1rem;">
								<?php global $mods_notWorkingCorrectly_dependenciesMissing; ?>
								<?php $missing_dependencies = @array_map("MainController::getTranslatedModNameByName", $mod_fragranceCollective->mod_missing_dependencies) ?: array(); ?>
								<?php echo $mods_notWorkingCorrectly_dependenciesMissing[$GLOBALS['lang']].implode(", ", $missing_dependencies); ?>.
							</div>
						</div>
					</section>

				<?php } ?>

			</div>
		</div>
	</div>
</div>

<?php $TC->the_footer('admin'); ?>
