<?php global $auth_modName, $auth_modDescription; ?>

<?php $isActive = $TC->isActiveMod('mod_auth'); ?>

<?php $TC->the_header('admin'); ?>
<?php $TC->the_navbar('admin'); ?>

	<div class="admin-bg"></div>

	<div class="admin-container navToggle"> <!-- .navToggle -->
		<div class="admin-container-left">
				<?php $TC->the_sidebar('admin'); ?>
			</div>
		<div class="admin-container-right">
			<div class="content-container">
				<div class="row">
					<?php
						$mod_header_data = array(
							"mod_name" => "mod_auth",
							"mod_name_lang" => $auth_modName[$GLOBALS['lang']],
							"mod_description" => $auth_modDescription[$GLOBALS['lang']]
						);
						$mod_header_conf = array(
							"checkbox_disabled" => true
						);
					?>
					<?php $TC->the_mod_header($mod_header_data, $mod_header_conf); ?>

					<?php
						// If module has been declared active
						if($isActive) {
					?>

						<section id="highlighted_layer" class="widget-squares col-md-12 row">
							<div class="col-md-12">
								<?php $TC->load_widget(array(
									"mod_name" => "mod_auth",
									"widget_name" => "profile_settings_widget"
								), ["mod_auth" => $TC->modules['mod_auth']], false); ?>
							</div>
						</section>

						<section class="widget-squares col-md-12 row">
							<div class="col-md-12"></div>
						</section>

					<?php } ?>

				</div>
			</div>
		</div>
	</div>

<?php $TC->the_footer('admin'); ?>
