<?php global $sensorResponder_modName, $sensorResponder_modDescription; ?>

<?php $mod_sensorResponder = $TC->modules['mod_sensorResponder'] ?? false; ?>

<?php $TC->the_header('admin'); ?>
<?php $TC->the_navbar('admin'); ?>

<div class="admin-bg"></div>

<div class="admin-container navToggle"> <!-- .navToggle -->
	<div class="admin-container-left">
				<?php $TC->the_sidebar('admin'); ?>
			</div>
	<div class="admin-container-right">
		<div class="content-container">
			<div class="row">
				<?php
					$mod_header_data = array(
						"mod_name" => "mod_sensorResponder",
						"mod_name_lang" => $sensorResponder_modName[$GLOBALS['lang']],
						"mod_description" => $sensorResponder_modDescription[$GLOBALS['lang']]
					);
				?>
				<?php $TC->the_mod_header($mod_header_data); ?>

				<?php if($mod_sensorResponder !== false && @$mod_sensorResponder->mod_isOperable) { ?>

					<section id="highlighted_layer" class="widget-squares col-md-12 row">
						<div class="col-md-12"><?php
							$TC->load_widget(array(
								"mod_name" => "mod_sensorResponder",
								"widget_name" => "spotify_liveticker_widget"
							), [], false);
						?></div>
					</section>

					<section class="widget-squares col-md-12 row">
						<div class="col-md-12"><?php
							$TC->load_widget(array(
								"mod_name" => "mod_sensorResponder",
								"widget_name" => "music_scent_management_widget"
							), [], false);
						?></div>
					</section>

				<?php } else if($mod_sensorResponder !== false && (bool)@$mod_sensorResponder->mod_isOperable === false) { ?>

					<section id="highlighted_layer" class="widget-squares col-md-12 row">
						<div class="col-md-12">
							<div class="card" style="padding: 0.25rem 1rem;">
								<?php global $mods_notWorkingCorrectly_dependenciesMissing; ?>
								<?php $missing_dependencies = @array_map("MainController::getTranslatedModNameByName", $mod_sensorResponder->mod_missing_dependencies) ?: array(); ?>
								<?php echo $mods_notWorkingCorrectly_dependenciesMissing[$GLOBALS['lang']].implode(', ', $missing_dependencies); ?>
							</div>
						</div>
					</section>
				<?php } ?>

			</div>
		</div>
	</div>
</div>

<?php $TC->the_footer('admin'); ?>
