<?php if(isset_true($MC->view['field_config']['container'])) { ?>
<div class="form-group form-group-sm <?php echo @$MC->view['field_config']['wrap_class'] ?: ""; ?>">
<?php } ?>

	<?php if(@$MC->view['field_config']['type'] !== "hidden") { ?>
		<label class="col-sm-6 control-label" for="<?php echo $MC->view['field_id']; ?>"><?php echo $MC->view['field_label']; ?></label>
	<?php } ?>

<?php if(isset_true($MC->view['field_config']['container'])) { ?>
	<div class="col-sm-6">
		<div class="field-container">
<?php } ?>
			<input
				type="<?php echo xssproof($MC->view['field_config']['type'] ?: 'text'); ?>"
				class="form-control input-sm <?php if(isset_true($MC->view['field_config']['inline'])) echo "col-md-6"; ?> <?php echo @$MC->view['field_config']['class'] ?: ""; ?>"
				name="<?php echo xssproof($MC->view['field_name']); ?>"
				value="<?php echo xssproof($MC->view['field_value']); ?>"
				id="<?php echo xssproof($MC->view['field_id']); ?>"
				placeholder="<?php echo xssproof($MC->view['field_config']['placeholder']); ?>"
				<?php if (isset_true($MC->view['field_config']['readonly'])) { ?>
					readonly="readonly"
				<?php } ?>
				<?php if (isSizedInt($MC->view['field_config']['maxlength'])) { ?>
					maxlength="<?php echo xssproof($MC->view['field_config']['maxlength']); ?>"
				<?php } ?>
				<?php if (isset_true($MC->view['field_config']['required'])) { ?>
					required
				<?php } ?>
				<?php if (isset_true($MC->view['field_config']['onkeyup'])) { ?>
					onkeyup="<?php echo $MC->view['field_config']['onkeyup']; ?>"
				<?php } ?>
				<?php if(isset_true($MC->view['field_config']['inline'])) { ?>
					style="display: inline; float: right;"
				<?php } ?>
			/>
			<?php if (isSizedString($MC->view['field_config']['help'])) { ?>
				<?php if ($MC->view['field_config']['rAlign']) { ?>
					<a href="#" data-wpsg-tip="<?php echo xssproof($MC->view['field_config']['help']); ?>" rel="?field=<?php echo xssproof($MC->view['field_config']['help']); ?>"
					   class="glyphicon glyphicon glyphicon-question-sign form-control-feedback float-right" aria-hidden="true"></a>
				<?php } else { ?>
					<a href="#" data-wpsg-tip="<?php echo xssproof($MC->view['field_config']['help']); ?>" rel="?field=<?php echo xssproof($MC->view['field_config']['help']); ?>"
					   class="glyphicon glyphicon glyphicon-question-sign form-control-feedback" aria-hidden="true"></a>
				<?php } ?>
			<?php } ?>
			<?php if($MC->view['field_config']['container']) { ?>
		</div>
	</div> <!-- .col-sm-6 -->
	<?php } # if($MC->view['field_config']['container']; ?>

	<?php if(isset($MC->view['field_config']['datepicker']) && $MC->view['field_config']['datepicker']) { ?>
		<?php
			$js = "$(document).ready(function() {";
				$js .= "$('#".xssproof($MC->view['field_id'])."').datepicker( { dateFormat: 'dd.mm.yy' } );";
			$js .= "} );";

			$GLOBALS['js']['field-'.$MC->view['field_id']] = array($js, []);
		?>
	<?php } ?>

	<div class="clearfix"></div>

<?php if(isset_true($MC->view['field_config']['container'])) { ?>
</div>
<?php } ?>