<?php if($MC->view['field_config']['container']) { ?>

	<div class="form-group form-group-sm <?php echo @$MC->view['field_config']['wrap_class'] ?: 0; ?>">

<?php } ?>

	<label class="col-sm-6 control-label" for="<?php echo $MC->view['field_id']; ?>"><?php echo $MC->view['field_label']; ?></label>

<?php if($MC->view['field_config']['container']) { ?>

	<div class="col-sm-6">
	<div class="field-container">

<?php } ?>
	<textarea
		class="form-control input-sm <?php echo @$MC->view['field_config']['class'] ?: ""; ?>"
		name="<?php echo xssproof($MC->view['field_name']); ?>"
		value="<?php echo xssproof($MC->view['field_value']); ?>"
		id="<?php echo xssproof($MC->view['field_id']); ?>"
		cols="<?php echo xssproof($MC->view['field_config']['cols']) ?>"
		placeholder="<?php echo xssproof($MC->view['field_config']['placeholder']); ?>"
		<?php if ($MC->view['field_config']['readonly']) { ?>
			readonly="readonly"
		<?php } ?>
		<?php if (isSizedInt($MC->view['field_config']['maxlength'])) { ?>
			maxlength="<?php echo xssproof($MC->view['field_config']['maxlength']); ?>"
		<?php } ?>
		<?php if ($MC->view['field_config']['required']) { ?>
			required
		<?php } ?>
		<?php if (isset($MC->view['field_config']['onkeyup'])) { ?>
			onkeyup="<?php echo $MC->view['field_config']['onkeyup']; ?>"
		<?php } ?>
	></textarea>
<?php if (isSizedString($MC->view['field_config']['help'])) { ?>
	<?php if ($MC->view['field_config']['rAlign']) { ?>
		<a href="#" data-wpsg-tip="<?php echo xssproof($MC->view['field_config']['help']); ?>" rel="?field=<?php echo xssproof($MC->view['field_config']['help']); ?>"
		   class="glyphicon glyphicon glyphicon-question-sign form-control-feedback float-right" aria-hidden="true"></a>
	<?php } else { ?>
		<a href="#" data-wpsg-tip="<?php echo xssproof($MC->view['field_config']['help']); ?>" rel="?field=<?php echo xssproof($MC->view['field_config']['help']); ?>"
		   class="glyphicon glyphicon glyphicon-question-sign form-control-feedback" aria-hidden="true"></a>
	<?php } ?>
<?php } ?>
<?php if($MC->view['field_config']['container']) { ?>
	</div>
	</div> <!-- .col-sm-6 -->
<?php } # if($MC->view['field_config']['container']; ?>

	<div class="clearfix"></div>

<?php if($MC->view['field_config']['container']) { ?>
	</div>
<?php } ?>