<?php
	/**
	 * @name: Timeline Widget
	 * @description: A widget to enable creating a new ticker tape
	 * @params: No additional params required
	 */
?>
<?php
	// Generate random and unique widget id
	$widget_id = uniqid();

	// Get module instance
	$mod_tickerTape = $TC->modules['mod_tickerTape'];
	// Get module data
	$mod_data = $mod_tickerTape->store;
?>

<style>
	#widget__timeline .timeline-inner { width: 100%; height: auto; min-height: 300px; }
	#widget__timeline .inner-container { width: 100%; position: relative; height: 100%; }

	#widget__timeline #timeline_create,
	#widget__timeline #timeline_edit { position: absolute; top: 0; bottom: 0; left: 0; right: 0; height: 100%; transition: 0.35s all ease-in-out; }
	#widget__timeline #timeline_create { cursor: pointer; z-index: 200; background: #fff; }
	#widget__timeline #timeline_create .title-box h1 { font-size: 30px; }
	#widget__timeline #timeline_create .title-box .create-icon { text-align: center; padding-top: 20px; font-size: 30px; }

	#widget__timeline #timeline_edit #timeline-controls { width: 250px; z-index: 200; transition: 0.25s all ease-in-out; position: absolute; top: 0; left: 0; bottom: 0; box-shadow: 0 0 10px rgba(0,0,0,0.30); }
	#widget__timeline #timeline_edit #timeline-controls.minimized { width: 100px; }
	#widget__timeline #timeline_edit #timeline-controls .vertical_hint__timeline_controls { transform: rotate(270deg); transform-origin: top left; font-family: "Montserrat", sans-serif; position: absolute; z-index: 999; font-weight: 700; left: 32%; top: 65%; font-size: 20px; }
	#widget__timeline #timeline_edit #timeline-controls .timeline-controls-main { margin-left: unset; margin-right: unset; }
	#widget__timeline #timeline_edit #timeline-controls .timeline-controls-expandable { position: absolute; top: calc(50% - 10px); right: -17px; cursor: pointer; }
	#widget__timeline #timeline_edit #timeline-controls .timeline-controls-expandable:before { content: ""; z-index: -1; position: absolute; top: -16px; right: -9px; width: 25px; height: 50px; background: #fff; border-bottom-right-radius: 50px; border-top-right-radius: 50px; box-shadow: 0 0 10px rgba(0,0,0,0.30) }
	#widget__timeline #timeline_edit #timeline-controls .form-control { border: 0; }
	#widget__timeline #timeline_edit #timeline-controls input.form-control { border-bottom: 1px solid rgba(0,0,0,0.30); border-radius: 1px; transition: 0.15s all ease-in-out; }
	#widget__timeline #timeline_edit #timeline-controls input.form-control:focus { box-shadow: none; border-bottom: 1px solid var(--primary-blue-alt); }
	#widget__timeline #timeline_edit #timeline-controls input.form-control ~ span { position: absolute; right: 45px; top: 12px; }
	#widget__timeline #timeline_edit #timeline-controls .form-control-btn-col { background: transparent; }
	#widget__timeline #timeline_edit #timeline-controls .form-control-btn-col button { margin: 0 auto;}
</style>

<!-- Widget -->
<div id="widget__timeline" class="widget-<?php echo $widget_id ?>">
	<div class="card" style="margin:0;overflow:hidden;">
		<div class="timeline-inner">
			<div id="timeline_create" class="inner-container flex-centered">
				<div class="title-box">
					<?php global $tickerTape_create; ?>
					<h1><?php echo $tickerTape_create[$GLOBALS['lang']]; ?></h1>
					<div class="create-icon">
						<i class="fas fa-plus-circle"></i>
					</div>
				</div>
			</div>
			<div id="timeline_edit" class="inner-container">

				<?php renderForm_init("?page=Admin&mod=mod_tickerTape&action=AddTickerTape", ["activate_card_wrap" => false]); ?>

					<div id="timeline-controls" class="flex-centered">
						<div class="timeline-controls-minimized dnone">
							<div class="vertical_hint__timeline_controls">
								<?php global $actions; ?>
								<?php echo $actions[$GLOBALS['lang']]; ?>
							</div>
						</div>
						<div class="timeline-controls-main row">
							<div class="formDiv form-control col-md-12 no-label">
								<?php global $title; ?>
								<?php renderForm_input("title", null, null, array(
									"type" => "text",
									"container" => false,
									"required" => true,
									"class" => isset_true($TC->view['title_err']['err_status']) ? "input-error" : "",
									"placeholder" => isset_true($TC->view['title_err']['err_status']) ? $TC->view['titlename_err']['err_msg'] : $title[$GLOBALS['lang']]));
								?>
							</div>
							<div class="formDiv form-control col-md-12 no-label">
								<?php global $totalTimeInMinutes, $minutes; ?>
								<?php renderForm_input("totaltime", null, null, array(
									"type" => "number",
									"container" => false,
									"required" => true,
									"class" => isset_true($TC->view['totaltime_err']['err_status']) ? "input-error" : "",
									"placeholder" => isset_true($TC->view['totaltime_err']['err_status']) ? $TC->view['totaltime_err']['err_msg'] : $totalTimeInMinutes[$GLOBALS['lang']]));
								?>
								<span class="text-muted totaltime-hint dnone no-transition"><?php echo $minutes[$GLOBALS['lang']]; ?></span>
							</div>
							<div class="formDiv form-control form-control-btn-col col-md-12 no-label" style="margin-top: 20px;">
								<?php global $form_save; ?>
								<button type="submit" class="btn-gradient btn-gradient-lbluegreen"><?php echo $form_save[$GLOBALS['lang']]; ?></button>
							</div>
							<div class="formDiv form-control form-control-btn-col col-md-12 no-label">
								<?php global $delete; ?>
								<button id="tickerTapeCancel" class="btn-gradient btn-gradient-red"><?php echo $delete[$GLOBALS['lang']]; ?></button>
							</div>
						</div>
						<div class="timeline-controls-expandable">
							<div class="timeline-open"><i class="fas fa-chevron-left"></i></div>
							<div class="timeline-close dnone"><i class="fas fa-chevron-right"></i></div>
						</div>
					</div>
					<div id="timeline" class="inner-container">

					</div>

				<?php renderForm_close("", array("activate_submit_btn" => false)); ?>

			</div>
		</div>
	</div>
</div>

<script>
	let timelineCreateSec = document.querySelector("#timeline_create");
	let timelineEditSec = document.querySelector("#timeline_edit");

	// Create new ticker tape
	timelineCreateSec.onclick = e => {
		e.preventDefault();

		timelineCreateSec.style.left = "-50000px";
	};

	/* Timeline controls */

	// Totaltime indicator
	const toggleTotalTimeIndicator = e => {
		e.target.nextElementSibling.nextElementSibling.style.display = (e.target.value.toString().trim().length > 0 ? "block" : "none");
	};

	timelineEditSec.querySelector("input[name='totaltime']").onkeyup = e => toggleTotalTimeIndicator(e);
	timelineEditSec.querySelector("input[name='totaltime']").onchange = e => toggleTotalTimeIndicator(e);

	// Cancel current ticker tape
	timelineEditSec.querySelector("#tickerTapeCancel").click = () => {
		// TODO: Clear all inputs and reslide in #timeline_create from left to right
	};

	timelineEditSec.querySelector(".timeline-controls-expandable").onclick = e => {
		let controlContainer = document.querySelector("#widget__timeline #timeline-controls");
		let verticalHint = document.querySelector(".timeline-controls-minimized");
		let mainControls = document.querySelector(".timeline-controls-main");
		let expandableBtn = document.querySelector(".timeline-controls-expandable");

		verticalHint.classList.toggle("dnone");
		mainControls.classList.toggle("dnone");
		controlContainer.classList.toggle("minimized");

		expandableBtn.childNodes.forEach(child => {
			if(!(child instanceof HTMLElement)) return;

			child.classList.toggle("dnone");
		});
	};
</script>
