<?php
	/**
	 * @name: Event Planner Widget
	 * @description: A widget to show planned events and to grant the opportunity to create events
	 * @params: No additional parameters required
	 */
?>

<?php global $name, $yes, $no, $type, $time, $date, $delete, $loop; ?>
<?php global $unit_ids, $event_deleteConfirmation_heading, $event_deleteConfirmation_text; ?>
<?php global $time_types_fragranceCollectiveSpray; ?>
<?php global $time_noEvent_addData, $time_actionArea__hint; ?>

<?php
	$TC->loadData('unit', 0);
	$unit_data = $TC->data['unit'][0];

	$mod_time = $TC->modules['mod_time'];
	$mod_data = $mod_time->store;
?>

<style>
	#event_planner_widget .widget_inner{ position: relative; width: 100%; height: 100%; }
	#event_planner_widget .widget_inner.slide-toggled .widget_table_area__container{ transition: 0.15s all ease-in-out; position: absolute; height: 100%; }
	#event_planner_widget .widget_inner .widget_table_area .btn-del{ margin-right: 5px !important; cursor: pointer; }
	#event_planner_widget .widget_inner .widget_table_area .btn-del i{ color: var(--red) !important; }
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area__container{ animation: 0.7s actionAreaExpand ease-in-out; transition: 0.15s all ease-in-out; width: 100%; border-left: 0 !important; background: #fff; }
	#event_planner_widget .widget_inner.slide-toggled .widget_table_area { display: none; }
	#event_planner_widget .widget_inner.slide-toggled .expand-action-area:before{ animation: 0.7s adjustExpandActionArea ease-in-out; background: #fff; color: #000; box-shadow: 0 2px 3px rgba(10,10,10,.1), 0 0 0 1px rgba(10,10,10,.1); }
	#event_planner_widget .widget_inner.slide-toggled .expand-action-area i{ animation: 0.7s adjustExpandActionAreaChevron ease-in-out; color: #000; transform: scale(-1, 1); margin-left: 5px; }
	#event_planner_widget .widget_inner.slide-toggled .vertical_hint__action_area{ display: none; height: 0; }
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area{ display: flex !important; animation: 0.7s actionAreaExpandContent ease-in-out; color: #000; height: 100%; width: 100%; padding: 20px; }
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area .action_area__inner{ position: relative; width: 100%; height: fit-content; }
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area .action_area__inner .action_area_header{ padding-bottom: 20px; }
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area .action_area__inner .action_area_header button,
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area .action_area__inner .action_area_header h1{ display: inline; }
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area .action_area__inner .action_area_header button{ float: right; }
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area .action_area__inner .form-control{ border: 0; background: transparent; }
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area .action_area__inner .form-control input[type="text"],
	#event_planner_widget .widget_inner.slide-toggled .widget_action_area .action_area__inner .form-control select{ background: var(--input-grey); color: rgba(0,0,0,0.7); }
	#event_planner_widget .widget_table_area__container{ position: relative; float: left; width: 95%; min-height: 270px; }
	#event_planner_widget .widget_action_area__container{ position: relative; float: left; width: 5%; background-image: linear-gradient(to right, #e43603, #e85a19); box-shadow: 0 4px 15px 0 rgba(229, 66, 10, 0.75); color: #fff; font-weight: bolder; border-left: 1px solid gray; }
	#event_planner_widget .widget_action_area__container .expand-action-area{ position: absolute; top: calc(50% - 10px); left: -20px; cursor: pointer; }
	#event_planner_widget .widget_action_area__container .expand-action-area:before{ content: ""; z-index: -1; position: absolute; top: -15px; left: -5px; width: 25px; height: 50px; background: #e43603; border-bottom-left-radius: 50px; border-top-left-radius: 50px; border-left: 1px solid gray; }
	#event_planner_widget .widget_action_area__container .expand-action-area i{ font-size: 20px; color: #fff; }
	#event_planner_widget .vertical_hint__action_area{ transform: rotate(90deg); transform-origin: top left; font-family: "Montserrat", sans-serif; text-shadow: -2px 3px 16px rgba(0, 0, 0, 0.3); position: absolute; z-index: 999; color: #fff; font-weight: 700; left: 70%; }

	@media only screen and (min-width: 320px) and (max-width: 917px) {
		#event_planner_widget .vertical_hint__action_area{
			display: none !important;
			height: 0px !important;
		}
	}

	@keyframes actionAreaExpand {
		0%{
			width: 5%;
			float: right;
			background: #e43603;
		}
		10%{
			width: 40%;
			float: right;
		}
		20%{
			width: 70%;
			float: right;
		}
		30%{
			width: 100%;
			float: right;
			border-left: 0;
		}
		100%{
			transition: 0.5s all ease-in-out;
			background: #fff;
		}
	}
	@keyframes actionAreaExpandContent {
		0%{ opacity: 0; }
		50%{ opacity: .3; }
		70%{ opacity: .7; }
		90%{ opacity: .9; }
		100%{ opacity: 1; }
	}
	@keyframes adjustExpandActionArea {
		0%{ background: #e43603; }
		100%{
			transition: 0.5s all ease-in-out;
			background: #fff;
			color: #000;
			box-shadow: 0 2px 3px rgba(10,10,10,.1), 0 0 0 1px rgba(10,10,10,.1);
		}
	}
	@keyframes adjustExpandActionAreaChevron {
		0%{ color: #fff; }
		100%{
			color: #000;
			transform: scale(-1, 1);
			margin-left: 5px;
		}
	}
</style>

<div class="event_planner_widget__wrapper">
	<div id="event_planner_widget" class="table_widget card card-flex">
		<div id="event_planner_widget__inner" class="widget_inner">
			<div class="widget_table_area__container">
				<div class="widget_table_area">
					<div class="widget-header">
						<h1>EVENTS</h1>
					</div>
					<?php if(isSizedArray($mod_data)) { ?>
						<table>
							<thead>
							<tr>
								<th>ID</th>
								<th><?php echo $name[$GLOBALS['lang']]; ?></th>
								<th><?php echo $type[$GLOBALS['lang']]; ?></th>
								<th><?php echo $unit_ids[$GLOBALS['lang']]; ?></th>
								<th><?php echo $time[$GLOBALS['lang']]; ?></th>
								<th><?php echo $date[$GLOBALS['lang']]; ?></th>
								<th><?php echo $loop[$GLOBALS['lang']]; ?></th>
							</tr>
							</thead>
							<tbody>
								<?php foreach($mod_data as $k => $event) { ?>
									<tr>
										<td>#<?php echo $event['event_id']; ?></td>
										<td>
											<?php $component_id = uniqid(); ?>
											<button type="button" class="no-btn btn-del trigger-component_modal-<?php echo $component_id; ?>">
												<i class="fas fa-times"></i>
											</button>
											<?php $TC->load_component("modal_confirmation", [
													"id" => $component_id,
													"title" => $event_deleteConfirmation_heading[$GLOBALS['lang']],
													"msg" => $event_deleteConfirmation_text[$GLOBALS['lang']],
													"accept_btn" => $delete[$GLOBALS['lang']],
													"accept_url" => "?page=Admin&mod=mod_time&action=deleteEvent&event_id=".$event['event_id']], false); ?>
											<?php echo ucfirst($event['event_name']); ?>
										</td>
										<td><?php echo @$mod_time->event_types_lang[ mod_time::EVENT_TYPES[(int)$event['event_type']] ] ?: $time_types_fragranceCollectiveSpray[$GLOBALS['lang']]; ?></td>
										<td><?php echo $event['event_targetUnits']; ?></td>
										<td><?php echo $event['event_plannedExecution_time']; ?></td>
										<td><?php echo DBDatetoDate($event['event_plannedExecution_date']) ?: "-"; ?></td>
										<td><?php echo (bool)$event['event_loop'] ? $yes[$GLOBALS['lang']] : $no[$GLOBALS['lang']]; ?></td>
									</tr>
								<?php } ?>
							</tbody>
						</table>
					<?php } else { ?>
						<div class="widget-header" style="border-top: 1px solid darkgray;">
							<h3><?php echo $time_noEvent_addData[$GLOBALS['lang']]; ?></h3>
						</div>
					<?php } ?>
				</div>
			</div>
			<div class="widget_action_area__container">
				<div class="vertical_hint__action_area flex-centered"><?php echo $time_actionArea__hint[$GLOBALS['lang']]; ?></div>
				<div class="expand-action-area"><i class="fas fa-chevron-left"></i></div>
				<div class="widget_action_area flex-centered" style="display: none;">
					<div class="action_area__inner">

						<?php renderForm_init("?page=Admin&mod=mod_time&action=addEvent", ["activate_card_wrap" => false]); ?>

							<div class="action_area_header">
								<h1 class="page-header" style="font-weight: 200;">
									<?php echo ucfirst($time_actionArea__hint[$GLOBALS['lang']]); ?>
								</h1>
								<button class="btn-gradient btn-gradient-blue" type="submit">
									<?php global $form_save; ?>
									<?php echo $form_save[$GLOBALS['lang']]; ?>
								</button>
							</div>

							<div class="formContainer row">
								<div class="formDiv form-control col-md-6">
									<?php global $form_eventName; ?>
									<?php renderForm_input("name", null, null, array(
										"type" => "text",
										"container" => false,
										"required" => true,
										"class" => isset_true($TC->view['eventname_err']['err_status']) ? "input-error" : "",
										"placeholder" => isset_true($TC->view['eventname_err']['err_status']) ? $TC->view['eventname_err']['err_msg'] : $form_eventName[$GLOBALS['lang']]));
									?>
								</div>
								<div class="formDiv form-control col-md-6">
									<?php global $form_eventType; ?>
									<?php $event_types_lang = array_values($mod_time->event_types_lang); ?>
									<?php array_unshift($event_types_lang, $form_eventType[$GLOBALS['lang']]); ?>
									<?php renderForm_select("type", null, $event_types_lang, 0, array("container" => false)); ?>
								</div>
								<div class="formDiv form-control col-md-6 no-label">
									<?php
										global $form_selectUnits, $event_noSchedulableUnits;
										$select_units = array($form_selectUnits[$GLOBALS['lang']]);
										$modal_data = array();

										foreach($unit_data as $i => $unit)
										{

											$name = "[#".$unit['unit_id']."] ".$unit['unit_name'];

											array_push($select_units, $name);

											if((bool)$unit['unit_isActivated'] === true && (bool)$unit['unit_isHub'] !== true)
												array_push($modal_data, ["id" => $unit['unit_id'], "name" => $name]);

										}
									?>
									<?php renderForm_select("units", null, $select_units, 0, array(
										"container" => false,
										"required" => true,
										"multiple" => true,
										"modal" => true,
										"nodata_text" => $event_noSchedulableUnits[$GLOBALS['lang']],
										"data" => $modal_data)); ?>
								</div>
								<div class="formDiv no-label form-control col-md-6">
									<?php global $form_eventDate; ?>
									<?php renderForm_input("date", null, null, array(
										"type" => "text",
										"container" => false,
										"required" => true,
										"datepicker" => true,
										"class" => isset_true($TC->view['eventdate_err']['err_status']) ? "input-error" : "",
										"placeholder" => isset_true($TC->view['eventdate_err']['err_status']) ? $TC->view['eventdate_err']['err_msg'] : $form_eventDate[$GLOBALS['lang']]));
									?>
								</div>
								<div class="formDiv form-control col-md-6">
									<?php global $form_eventTime; ?>
									<?php renderForm_timepicker("time", $form_eventTime[$GLOBALS['lang']], "", ["container" => true]); ?>
								</div>
								<div class="formDiv form-control col-md-6">
									<?php renderForm_toggleSwitch("loop", "Wiederholung", false, array(
										"container" => false,
										"standard_css" => true
									)); ?>
								</div>
							</div> <!-- .formContainer -->

						<?php renderForm_close("", array("activate_submit_btn" => false)); ?>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	let qs = document.querySelector.bind(document);

	/* UI Calculation */
	let tableAreaCont = qs(".widget_table_area__container");
	let actionAreaCont = qs(".widget_action_area__container");
	let actionAreaHint = qs(".vertical_hint__action_area");

	let adjustAreaHeight = () => {
		actionAreaCont.style.height = tableAreaCont.offsetHeight;

		actionAreaHint.style.width = actionAreaCont.style.height;
	};

	/* Add Event Visual Appeal Functionality */
	let actionAreaSlided = false;
	let slideBackTriggerClasses = ["expand-action-area", "fa-chevron-left", "vertical_hint__action_area"];

	let addEvent_sliding = e => {

		let isValidSlideBackTrigger = classes => {
			let ret = false;

			Array.from(classes).forEach(className => {

				if(slideBackTriggerClasses.includes(className))
					ret = true;

			});

			return ret;
		};

		if(
			actionAreaSlided &&
			!isValidSlideBackTrigger(e.srcElement.classList)
		) return false;

		actionAreaSlided = !actionAreaSlided;
		qs('#event_planner_widget__inner').classList.toggle("slide-toggled");
	};

	/* Event Binding */
	// Onload
	adjustAreaHeight();

	// Onresize
	window.addEventListener("resize", adjustAreaHeight);

	// Onclick
	actionAreaCont.addEventListener("click", addEvent_sliding);
	actionAreaHint.addEventListener("click", addEvent_sliding);
</script>