<?php

	/**
	 * Template to continue the process of password recovery
	 * At this point the user has already clicked the link in the email sent
	 */

	$TC->the_header('mod_auth');
	$TC->the_navbar('mod_auth');

	if(!isSizedString($_REQUEST['selector']) && !isSizedString($_REQUEST['token']))
		die('Illegal request');

	global $auth_recover_pw, $auth_new_pw;
	global $form_reset, $form_cancel;

	try{
		// Check if selector and token are valid
		$TC->modules['mod_auth']->Auth->canResetPasswordOrThrow($_REQUEST['selector'], $_REQUEST['token']);

		// Get new password and reset the existing onw
		if(isSizedString($_REQUEST['password']))
		{

			$TC->modules['mod_auth']->Auth->resetPassword($_REQUEST['selector'], $_REQUEST['token'], $_REQUEST['password']);

			// Success
			$TC->redirect("/login", true);

		}
		else
		{
			// Ask for the new password
			?>

			<div class="auth row">
				<div class="col-md-8 layer-login flex-centered m-auto">
					<div class="content">
						<h1><?php echo $auth_recover_pw[$GLOBALS['lang']]; ?></h1>
						<?php renderForm_init("?/reset_password"); ?>
						<?php
							renderForm_input("selector",null, $_REQUEST['selector'],
								array("type" => "hidden"));
						?>
						<?php
							renderForm_input("token",null, $_REQUEST['token'],
								array("type" => "hidden"));
						?>
						<?php
							renderForm_input("password", null, null, array(
									"type" => "password",
									"container" => false,
									"required" => true,
									"class" => "",
									"placeholder" => "&#xf023   ".$auth_new_pw[$GLOBALS['lang']])
							);
						?>
						<span class="reset-pw"><a href="/login"><?php echo $form_cancel[$GLOBALS['lang']]; ?></a></span>
						<button href="#" class="button" type="submit"><?php echo $form_reset[$GLOBALS['lang']]; ?></button>
						<?php renderForm_close("", array("activate_submit_btn" => false)); ?>
					</div>
				</div>
			</div>

			<?php
		}
	}
	catch (InvalidSelectorTokenPairException $err) {
		global $invalid_selector_token_pair;
		echo $invalid_selector_token_pair[$GLOBALS['lang']];
	}
	catch (TokenExpiredException $err) {
		global $token_expired;
		echo $token_expired[$GLOBALS['lang']];
	}
	catch (ResetDisabledException $err) {
		global $reset_disabled;
		echo $reset_disabled[$GLOBALS['lang']];
	}
	catch (InvalidPasswordException $err) {
		global $invalid_password;
		echo $invalid_password[$GLOBALS['lang']];
	}
	catch (TooManyRequestsException $err) {
		global $too_many_requests;
		echo $too_many_requests[$GLOBALS['lang']];
	}

	$TC->the_footer('mod_auth');
